Apply deltaTimer and minor code improvements
TheEmperorsArmoury/TheGreatWar pull request #22
Opened 2024-06-21 18:15 UTC by danieldownes

2024-06-21 18:15 UTC, danieldownes commented on SandSim2000/AgentManager.cpp
> -
Would say this is not needed, is outdated, in the wrong place and/or is just in the way.

2024-06-21 18:17 UTC, danieldownes commented on SandSim2000/Camera.cpp
> +    text1.setPosition(10, 10);
Our code-formating rules at play tore move white-space at the end of files. I've rarely seen this happen, so must have been some dev habbit.

2024-06-21 18:18 UTC, danieldownes commented on SandSim2000/GridGenerator.cpp
> -*/
If its important, then the dev who finds it important tag/bookmark the code in github, or save locally. We don't need useless code in the codebase.

2024-06-21 18:19 UTC, danieldownes reviewed
Added some initial comments to show my thoughts.
It may be best to see diffs on a per commit basis as there is a bit of code formatting as previously warned.

2024-06-21 18:24 UTC, danieldownes commented
@LiamStewart2 Please can you also review, not just functionality, but the code changes if you can wade through the formatting changes..

2024-06-22 09:44 UTC, 123samueld commented on SandSim2000/AgentManager.cpp
> -
I'm all for code which is purely self commenting, so removing is a great idea. Just I received some flakk about no "comments" so put this as a compromise. But self commenting code (clean, polite code that reads like well written pros) is superior to comments.

2024-06-22 09:47 UTC, 123samueld commented on SandSim2000/BattlefieldMap.cpp
> -    */
Agreed. Handy to quickly switch to flat terrain but not needed most of the time.

2024-06-22 10:00 UTC, 123samueld commented on SandSim2000/Camera.cpp
> +    text1.setPosition(10, 10);
Not entirely sure what you mean, could you elaborate a little?

2024-06-22 10:01 UTC, 123samueld commented on SandSim2000/GridGenerator.cpp
> -*/
Agreed. I wrote that and left it commented out, bad housekeeping on my part.

2024-06-23 15:18 UTC, danieldownes commented on SandSim2000/Camera.cpp
> +    text1.setPosition(10, 10);
Sure, you can see the end of files previously had a space at the end? Applying the code-formatting rule (VS shortcut Control-k+d chord), as defined in .clang-format file removed them. Just throught I'd point this out as I've rarely see extra spaces at the end of lines.

2024-06-24 13:22 UTC, danieldownes commented
@123samueld This is now merged, however there is a call to console log: [INVALID SPRITE POSITION]
I don't know why, perhaps you can have a dig in?

2024-06-25 08:09 UTC, 123samueld commented
> @123samueld I've now resolved the merge comments with main, however now there is a call to console log: [INVALID SPRITE POSITION]
> 
> I don't know why, perhaps you can have a dig in?
I'm not getting that error, can you tell me how to replicate it?

2024-06-25 08:15 UTC, 123samueld commented
> Objectives:
> 
> * Introduce a shared deltaTime calc.
> * See the automated code-formatting in action.
> * Reduce some x/y pairs in the Camera class to vector2.
> * Slowdown the mobileAgent that follows the pathfinderAgent.
> * Remove the pathfinderAgent sprite.
> 
> I believe ensuring pathfinding for mobileAgent may be an appropriate task to discuss. I don't believe this was quite working in the PR discussed earlier. The pathfinderAgent and mobileAgent need to be synced. Currently there is no timing sync happening which causes the mobileAgent to not care about pathfinding, and is only using pathfindingAgent as a waypoint marker.

Dan, yes the mobileAgents don't directly pathfind themselves. This is intentional, because the attempt was to build an RTS about The Great War, there would be a colossal number of units and all those pathing sessions would get expensive. So instead there is a pathfinderAgent for each pathing session, whether it's just 1 unit moving or a group of 100. Then the Boids (mobileAgents) flock around the pathfinderAgent as it moves creating an organic group movement at relatively low cost. Hence why the speed of the pathfinderAgent is way too high, it will need to be better matched to the speed of it's mobileAgent, but that's for later once we have multiple mobileAgents.

2024-06-25 08:54 UTC, danieldownes commented
> Please check my responses to 2 of your comments.
> 
> You mentioned an error "Invalid Sprite Position", I didn't get it, can you tell me how to replicate it?
> 
> Apart from that I'd approve this.

Its not an error. Its a log in the console window.

2024-06-25 09:25 UTC, 123samueld commented
> > Please check my responses to 2 of your comments.
> > You mentioned an error "Invalid Sprite Position", I didn't get it, can you tell me how to replicate it?
> > Apart from that I'd approve this.
> 
> Its not an error. Its a log in the console window.

I'm not getting anything like that in the console, neither in MapEditor nor Skirmish modes. But there are some other comments, like "MapEditor" and what I assume is pathfinding execution time logs. Please remove all console comments before moving on.

2024-06-25 10:38 UTC, 123samueld requested changes
Please remove the debuggin/prototype comments ("Map Editor Selected" and numbers like 0: 0.121221 etc) then this will be ready to merge.

2024-06-25 11:48 UTC, danieldownes commented
> Please remove the debuggin/prototype comments ("Map Editor Selected" and numbers like 0: 0.121221 etc) then this will be ready to merge.

I think that's being a bit fussy for the purpose of this PR. So I don't agree.

2024-06-25 13:18 UTC, 123samueld approved these changes
Thank you for applying timeDelta, that's a much better way to handle time shifts, I got complacent using SMLF's FPS limiter.

Merge when ready.

2024-06-25 13:25 UTC, merged